#!/bin/bash

HERE=$(pwd)

if git status >/dev/null 2>&1; then

    echo "ERROR: Not empty directory '$HERE'"
    echo "Please clone into the empty direcotry!"
    exit 1
fi

if [ -z "$1" ]; then

    echo "ERROR: Repository parameter is mandatory"
    exit 1
fi

REPO="$1"

echo "Cloning from remote repository: $REPO"

if git clone "$REPO"; then

    echo "Clone ok"

    if git submodule init; then

        if git submodule update; then

            echo "Submodules are ready"

        else

            echo "ERROR: Submodules update failed"
            exit 1
        fi

    else

        echo "ERROR: Submodules init failed"
        exit 1
    fi

else

    echo "Clone operation failed"
    exit 1
fi