#!/bin/bash

# TODO: Clone script to download the opening files and scripts that are not the part of Project Toolkit

HERE=$(pwd)

SCRIPT_DO_OPEN="$HERE/do_open"
SCRIPT_PRE_OPEN="$HERE/pre_open"
SCRIPT_POST_OPEN="$HERE/post_open"

if test -e "$SCRIPT_PRE_OPEN"; then

    if ! sh "$SCRIPT_PRE_OPEN"; then

        echo "ERROR: Pre-open failed"
        exit 1
    fi
fi


SCRIPT_PREPARE_LOCAL="$HERE/prepare"

if ! test -e "$SCRIPT_PREPARE_LOCAL" || ! test -e "$SCRIPT_DO_OPEN"; then

    SCRIPT_PREPARE_TOOLKIT="$SUBMODULES_HOME/prepare"

    if test -e "$SCRIPT_PREPARE_TOOLKIT"; then

        if ! sh "$SCRIPT_PREPARE_TOOLKIT"; then

            echo "ERROR: Script failed '$SCRIPT_PREPARE_TOOLKIT'"
            exit 1
        fi

    else

        echo "ERROR: Script not found '$SCRIPT_PREPARE_TOOLKIT'"
        exit 1
    fi
fi

if test -e "$SCRIPT_DO_OPEN"; then

  sh "$SCRIPT_DO_OPEN"

fi

if test -e "$SCRIPT_POST_OPEN"; then

    if ! sh "$SCRIPT_POST_OPEN"; then

        echo "ERROR: Post-open failed"
        exit 1
    fi
fi
