#!/bin/bash

HERE="$(pwd)"
SCRIPT_PREPARE="$HERE/prepare"

if ! test -e "$SCRIPT_PREPARE"; then

    echo "ERROR: Script not found '$SCRIPT_PREPARE'"
    exit 1
fi

# shellcheck disable=SC1090
. "$SCRIPT_PREPARE"

SCRIPT="$HERE/Run/Project/open.sh"

if ! test -e "$SCRIPT"; then

    echo "ERROR: Script not found at $SCRIPT"
    exit 1
fi

ASCII_ART="$HERE/Assets/ASCII_Art.txt"

if test -e "$ASCII_ART"; then

    echo && cat "$ASCII_ART" && echo
fi

sh "$SCRIPT"