#!/bin/bash

# Install Software-Toolkit if not available - Via Dependable?

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: The SUBMODULES_HOME is not defined !!!"
  exit 1
fi

SCRIPT_PREPARE="$SUBMODULES_HOME/Project/prepare.sh"

if ! test  -e "$SCRIPT_PREPARE"; then

    echo "ERROR: Prepare script not found '$SCRIPT_PREPARE'"
    exit 1
fi

HERE=$(dirname "$(realpath "$0")")

if ! sh "$SCRIPT_PREPARE" "$HERE"; then

    echo "ERROR: Project prepare failed"
    exit 1
fi

# TODO: Move all below to the Project module, then include here
# TODO: Check submodules home handling below - is it obsolete? Adding it into the .rs file to be moved into
#       the Project Toolkit's installation recipe

HERE="$(dirname -- "$0")"
DIR_HOME=$(eval echo ~"$USER")
FILE_ZSH_RC="$DIR_HOME/.zshrc"
FILE_BASH_RC="$DIR_HOME/.bashrc"

FILE_RC=""
    
if test -e "$FILE_ZSH_RC"; then

  FILE_RC="$FILE_ZSH_RC"

else

    if test -e "$FILE_BASH_RC"; then

      FILE_RC="$FILE_BASH_RC"

    else

      echo "ERROR: No '$FILE_ZSH_RC' or '$FILE_BASH_RC' found on the system"
      exit 1
    fi
fi

# shellcheck disable=SC2002
if ! cat "$FILE_RC" | grep "SUBMODULES_HOME=" >/dev/null 2>&1; then

    if echo "" >> "$FILE_RC" && echo "export SUBMODULES_HOME=$HERE/_Submodules" >> "$FILE_RC"; then

        echo "SUBMODULES_HOME is added into '$FILE_RC' configuration"

    else

        echo "WARNING: SUBMODULES_HOME was not added into '$FILE_RC' configuration"
    fi
fi

if test -e "$SUBMODULES_LOAD_ENVIRONMENT"; then

    echo "Loading the environment"
    
    # shellcheck disable=SC1090
    . "$SUBMODULES_LOAD_ENVIRONMENT" >/dev/null 2>&1
fi

DIR_MODULE_UPSTREAMABLE="$SUBMODULES_HOME/Upstreamable"

ADD_TO_PATH() {

    if [ -z "$1" ]; then

        echo "ERROR: RC file path is mandatory parameter"
        exit 1
    fi

    if [ -z "$2" ]; then

        echo "ERROR: Directory is mandatory parameter"
        exit 1
    fi

    FILE_RC="$1"
    DIR_PATH="$2"

    # shellcheck disable=SC2002
    if ! cat "$FILE_RC" | grep "$DIR_PATH" >/dev/null 2>&1; then

        LINE_TO_ADD="export PATH=\${PATH}:$DIR_PATH"

        if echo "" >> "$FILE_RC" && echo "$LINE_TO_ADD" >> "$FILE_RC"; then

            echo "Module path '$DIR_PATH' is added into '$FILE_RC' configuration"
            
        else

            echo "WARNING: Module path '$DIR_PATH' was not added intp '$FILE_RC' configuration"
        fi
    fi
}

ADD_TO_PATH "$FILE_RC" "$DIR_MODULE_UPSTREAMABLE"

# shellcheck disable=SC1090
. "$FILE_RC"

if [ -n "$SUBMODULES_PRIVATE_HOME" ] && [ -n "$SUBMODULES_PRIVATE_RECIPES" ]; then
    
    SCRIPT_INSTALL_PRIVATE_MODULES="$SUBMODULES_HOME/Software-Toolkit/Utils/Git/install_private_submodules.sh"

    if ! test -e "$SCRIPT_INSTALL_PRIVATE_MODULES"; then

        echo "ERROR: Script not found '$SCRIPT_INSTALL_PRIVATE_MODULES'"
        exit 1
    fi

    if ! sh "$SCRIPT_INSTALL_PRIVATE_MODULES" "$SUBMODULES_PRIVATE_HOME" "$SUBMODULES_PRIVATE_RECIPES"; then

        echo "ERROR: Private modules installation failed"
        exit 1
    fi
fi
