#!/bin/bash

if git fetch; then

  if git pull; then

    if git submodule init; then

      if git submodule update; then

        echo "Update OK"

      else

        echo "ERROR: Could not update (4)"
        exit 1
      fi

    else

      echo "ERROR: Could not update (3)"
      exit 1
    fi

  else

    echo "ERROR: Could not update (2)"
    exit 1
  fi

else

  echo "ERROR: Could not update (1)"
  exit 1
fi