#!/bin/bash
export VERSIONABLE_SNAPSHOT=true
export VERSIONABLE_NAME="Helix Track - Core"
export VERSIONABLE_VERSION_PRIMARY="1"
export VERSIONABLE_VERSION_SECONDARY="0"
export VERSIONABLE_VERSION_PATCH="0"
