#!/bin/bash
export VERSIONABLE_SNAPSHOT=true
export VERSIONABLE_NAME="htCore"
export VERSIONABLE_VERSION_PRIMARY="0"
export VERSIONABLE_VERSION_SECONDARY="0"
export VERSIONABLE_VERSION_PATCH="1"
export VERSIONABLE_HOMEPAGE="https://www.helixtrack.io/"
export VERSIONABLE_DESCRIPTION="HelixTRack Core."
